name = "TrixiEnzyme"
uuid = "5c65496b-8c34-42ae-b83c-c141bd4a07ce"
authors = ["Junyi Xu <junyixu0@gmail.com>"]
version = "0.1.0"

[deps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
